### ISSUE TITLE
Syntax Error: Unexpected token: name (params)

### ISSUE THREAD

**Issue by Xarkam** [HookyQR/VSCodeMinify#24]
Hello,

I try to minify my code and I receive this laconic error message:

`Minify Failed: Syntax Error: Unexpected token: name (params)`

How to see log from extension ?

**Comment by Xarkam** [comment]
Fixed.

Ufligy-js doesn't support es6. 

Need to use `uglify-es` for that.

**Comment by osotorrio** [comment]
I have the same problem.

Did you include uglify-es in this extension?...or you just used in as a separated tool?

Thanks
