### ISSUE TITLE
Minify on save

### ISSUE THREAD

**Issue by matrixapps** [HookyQR/VSCodeMinify#26]
Hi,

Recently updated VScode t o 1.25.1 and noticed that my js files are no longer minifying on save.  Is this a known issue?  Something I could check?  Thanks!

**Comment by cemerson** [comment]
I may be dealing w/something else but I'm having same issue. I have the "minify.minifyExistingOnSave" setting set to true in my VSCode workspace settings, and when I save the file my status bar says "Minified: 42% of original" ... but the .min file isn't updated (and no new file is created either). 

FWIW if I select "Minify" from the command palette the same thing happens: "Minified" message in the status bar but no .min file is created or updated.
