### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jft-id** [HookyQR/VSCodeMinify#31]
- Issue Type: `Performance`
- Extension Name: `minify`
- Extension Version: `0.3.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/apple/HookyQR.minify-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by HookyQR** [comment]
And the file?

**Comment by jft-id** [comment]
[HookyQR.minify-unresponsive.cpuprofile.txt](https://github.com/HookyQR/VSCodeMinify/files/2877814/HookyQR.minify-unresponsive.cpuprofile.txt)
Here is the file. Thanks and sorry for the miss.

**Comment by HookyQR** [comment]
I've pushed a new version which may resolve this, let me know how version 0.4.0 performs for you.
