### ISSUE TITLE
Doesn't minify

### ISSUE THREAD

**Issue by ScrippsFEE** [HookyQR/VSCodeMinify#32]
I installed this extension in VS Code. Opened a JS file and ran the Minify command, but nothing happened. Shouldn't it work on the currently opened file in the editor? 

 Am I missing something? 

<img width="1045" alt="no-minify" src="https://user-images.githubusercontent.com/4502870/54374100-c9e5f980-4654-11e9-898e-3b3625af2119.png">

**Comment by HookyQR** [comment]
Fixed in 0.4.0. (uglify-js didn't support es6)
