### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by venki208** [HookyQR/VSCodeMinify#33]
- Issue Type: `Performance`
- Extension Name: `minify`
- Extension Version: `0.3.0`
- OS Version: `Linux x64 3.13.0-166-generic`
- VSCode version: `1.32.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/venkatesh/HookyQR.minify-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by HookyQR** [comment]
Dup of #31.
