### ISSUE TITLE
Extension host crashes on minify 0.4.0

### ISSUE THREAD

**Issue by Eupeodes** [HookyQR/VSCodeMinify#35]
With 0.4.0 the extension host crashes every time I try to minify my js files. Content of js file doesn't matter (I even tried with a simple "console.log('Hello world')" and got the crash. 0.3.0 works fine
I am using visual studio code 1.32.3 on Windows 10 Pro 1809.

As temporary fix I reverted the extension to 0.3.0 and disable auto update of extensions.

Update: it seems it is caused by having the default settings as listed on in the extension page all in the settings.json of the project, as soon as I remove that block minify works.

**Comment by HookyQR** [comment]
Ah, some of the settings listed there are invalid now because of the move from uglify to terser. Will update the readme.

The offenders are `cascade` (removed) and `bracketize` becomes `braces`.

**Comment by HookyQR** [comment]
0.4.1 published.
