### ISSUE TITLE
Minify Failed: 'preserve_line' is not a supported option

### ISSUE THREAD

**Issue by Niush** [HookyQR/VSCodeMinify#43]
Minify Failed: 'preserve_line' is not a supported option

**Comment by ChiseCJ** [comment]
I have the same problem. I don't know how to solve it.

**Comment by gmarais** [comment]
Going into the settings and removing the setting all together worked for me.
the correct setting should be preserveLineBreaks anyways as in the package file I suppose.

**Comment by barguti** [comment]
I have the same problem too🙄🤔

**Comment by voaneves** [comment]
Trying to minify JS, always this warning "preserve_line is not an option. My current JS configs:

```
"minify.js": {
    "mangle": true,
    "compress": {
      "sequences": true,
      "properties": true,
      "dead_code": true,
      "drop_debugger": true,
      "unsafe": false,
      "unsafe_comps": false,
      "conditionals": true,
      "comparisons": true,
      "evaluate": true,
      "booleans": true,
      "loops": true,
      "unused": true,
      "hoist_funs": true,
      "keep_fargs": true,
      "keep_fnames": false,
      "hoist_vars": false,
      "if_return": true,
      "join_vars": true,
      "collapse_vars": false,
      "reduce_vars": false,
      "side_effects": true,
      "pure_getters": false,
      "pure_funcs": null,
      "negate_iife": false,
      "drop_console": false,
      "passes": 1,
      "global_defs": {}
    },
    "output": {
      "ascii_only": false,
      "inline_script": false,
      "max_line_len": 32000,
      "braces": false,
      "semicolons": true,
      "comments": false,
      "shebang": true,
      "preamble": null,
      "quote_style": "best"
    }
  }
```

There's no preserve_line on the settings.json

**Comment by jgangatharan** [comment]
Have same problem. "minify.js": {
    "mangle": true,
    "compress": {
        "sequences": true,
        "properties": true,
        "dead_code": true,
        "drop_debugger": true,
        "unsafe": false,
        "unsafe_comps": false,
        "conditionals": true,
        "comparisons": true,
        "evaluate": true,
        "booleans": true,
        "loops": true,
        "unused": true,
        "hoist_funs": true,
        "keep_fargs": true,
        "keep_fnames": false,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "collapse_vars": false,
        "reduce_vars": false,
        "side_effects": true,
        "pure_getters": false,
        "pure_funcs": null,
        "negate_iife": false,
        "drop_console": false,
        "passes": 1,
        "global_defs": {}
    },
    "output": {
        "ascii_only": false,
        "inline_script": false,
        "max_line_len": 32000,
        "braces": false,
        "semicolons": true,
        "comments": false,
        "shebang": true,
        "preamble": null,
        "quote_style": "best"
    }
},
